namespace SimpleMathComponent
{
    [default_interface]
    //[webhosthidden]
    runtimeclass BoxRenderer : Microsoft.UI.Xaml.Controls.ContentControl
    {
        BoxRenderer();
        //static Microsoft.UI.Xaml.DependencyProperty BoxSizeProperty{ get; };
        //Int32 BoxSize;
        // Int32 Width;
        // Int32 Height;
    }
}
